plugins {
    alias(libs.plugins.android.library)
}
apply from: "../../common.gradle"

android {
    namespace "de.danoeh.antennapod.parser.feed"
    lint {
        disable 'DuplicatePlatformClasses'
    }
}

dependencies {
    implementation project(':model')
    implementation project(':net:common')
    implementation libs.okhttp

    annotationProcessor libs.androidx.annotation

    implementation libs.androidx.core

    implementation libs.commons.lang3
    implementation libs.commons.io
    implementation libs.jsoup
    implementation libs.json

    testImplementation libs.junit
    testImplementation libs.robolectric
}
